### ISSUE TITLE
Insignia on Gun

### ISSUE THREAD

**Issue by PashaSynthax** [PolyacovYury/PYmods#19]
Hey idk anything about make mods can u pls update the insignia on Gun mod?

**Comment by PolyacovYury** [comment]
Hello :)
I just checked, and InsigniaOnGun mod appears to be still working both in battle and in lobby on RU version and in lobby on EU version. You would only need to re-name the versioned folder, if you downloaded it as an archive, or just drop the .wotmods into the relevant game client's folder, if you are compiling the repo yourself.
Side note: until further notice, compiled/packed mods will be distributed via my "Gloomy Bunker" mod pack, since the .exe-installer allows me to change the versioned folder's name based on the game client's region without packing/uploading mods' files twice.

If there are any problems I haven't noticed - feel free to re-open this issue, describe them and attach your `python.log` file, which you can locate next to your WorldOfTanks.exe.

**Comment by PashaSynthax** [comment]
Hey,

Thanks for the reply
i got this error and i dont understand all this sry :(
https://prnt.sc/OeIjEwVmgmWC

**Comment by PashaSynthax** [comment]
[python.log](https://github.com/user-attachments/files/16683232/python.log)
